apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  labels:
    {{- include "deegree-inspire.labels" . | nindent 4 }}
type: Opaque
data:
  password: bm90aGluZyBwdw==
  username: bm9ib2R5