apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
    {{- include "deegree-inspire.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "deegree-inspire.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: 8080
  